name: 'Close stale issues'
on:
  schedule:
  - cron: '* * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{secrets.YARNBOT_TOKEN}}

        stale-issue-message: |
          Hi! 👋

          This issue looks stale, and doesn't feature the 'reproducible' label - which implies that you didn't provide a working reproduction using [Sherlock](https://yarnpkg.com/advanced/sherlock). As a result, it'll be closed in a few days unless a maintainer explicitly vouches for it.

          Note that we require Sherlock reproductions for long-lived issues (rather than standalone git repositories, for example) because we're a small team. Sherlock gives us the ability to check which bugs are still affecting the master branch at any given point, and decreases the amount of code we need to run on our own machines (thus leading to faster bug resolution faster).

          If you absolutely cannot reproduce a bug on Sherlock (for example because it's Windows-only), a maintainer will have to manually add the 'unholded' label.

        debug-only: true
        remove-stale-when-updated: false

        days-before-stale: 30
        days-before-close: 5

        only-labels: 'bug'

        stale-issue-label: 'stale'
        exempt-issue-labels: 'reproducible,upholded'
